import {CSSProperties} from 'react';

export let useLoginStyles = (): {[key: string]: CSSProperties} => ({
	loginRoot: {
		textAlign: 'center',
		color: '#2c3e50',
		position: 'fixed',
		top: 0,
		left: 0,
		bottom: 0,
		right: 0,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	loginCard: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		width: '47.2%',
		maxWidth: '410px',
		maxHeight: '450px',
		minWidth: '240px',
		minHeight: '320px',
		background: '#ffffff',
		borderRadius: '2px',
		boxShadow: '2px 0px 10px rgba(0,0,0,0.16)',
	},
	loginCardContent: {
		display: 'flex',
		width: '100%',
		height: '100%',
		justifyContent: 'space-between',
		alignItems: 'center',
		flexDirection: 'column',
		padding: '10% 10% 5%',
		maxHeight: '90vh',
	},
	loginCaption: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		marginBottom: '5%',
		fontFamily: 'sans-serif',
		fontWeight: 600,
		fontSize: '24px',
		color: '#412d41',
		maxWidth: '75%',
		width: '75%',
		overflow: 'hidden',
		maxHeight: '30vh',
	},
	loginDescription: {
		fontSize: '14px',
		marginTop: '10%',
		fontWeight: 400,
		letterSpacing: '1px',
		lineHeight: '2em',
	},
	loginForm: {
		display: 'flex',
		flexDirection: 'column',
		margin: '0 0 5%',
		width: '80%',
	},
	loginFormInput: {
		fontFamily: 'sans-serif',
		marginBottom: '10%',
		height: '38px',
		fontSize: '14px',
		borderRadius: '5px',
		background: 'rgb(253, 208, 124)',
		border: '2px solid rgb(230, 230, 230)',
		padding: '0 15px',
		color: '#412d41',
	},
	loginFormButton: {
		fontFamily: 'sans-serif',
		width: '100%',
		height: '66px',
		fontWeight: 600,
		fontSize: '14px',
		borderRadius: '33px',
		background: 'rgb(253, 208, 124)',
		border: '2px solid rgb(230, 230, 230)',
		color: '#412d41',
		cursor: 'pointer',
	},
	loginFormValidationMessage: {
		minHeight: '14px',
		height: '14px',
		overflow: 'hidden',
	},
});
